Jsonapi integration
PBI22/Agil-Flask-Note-Projekt pull request #26
Opened 2024-03-18 11:36 UTC by MartinDP333

Der er blevet tilføjet et api endpoint
url/api/endpoint

Der er blevet tilføjet noteJSON endpoint som lige nu viser alle noter
(senere kommer der mulighed for at vise kun en note med en parameter)

2024-03-18 11:46 UTC, zteffano requested changes
**Fedt den har fået sin egen side!**

1. Men er det nødvendig med SÅ mange imports ?  Det ser ud til mange ikke bliver brugt og der kunne måske blive nogle relative import issues.

2.  Når nu Sune har sat ORM om og vi allerede har en database connection igennem det. Kan vi så ikke bare bruge den ? Tænker vi bør undgå at skulle hardcode SQL queries ligesom.  + det bliver noget nemmere med ORM. Se evt. hvordan den henter noter fra Database i view functionen.

har lagt lige kommentarer ind i koden

2024-03-18 11:47 UTC, zteffano commented on hello_app/API.py
> +    json_data = json.dumps(data_list, indent=4)
Kan ikke lige spotte hvad denne bliver brugt til ?

2024-03-18 12:21 UTC, MartinDP333 commented
Bruger nu ORM og har fjernet unødvendige imports
mangler stadigvæk at tilføje mulighed mellem 1 eller alle noter

2024-03-18 12:37 UTC, MartinDP333 commented on hello_app/API.py
> +    json_data = json.dumps(data_list, indent=4)
fjernet

2024-03-19 08:20 UTC, zteffano requested changes
Fedt med  /api/ prefix og lavet som blueprint.

Husk at få pullet fra main og tjekket op, da du har alt det der lagt over i /notes/ med i din views. Det vil skabe unødige endpoints.

Ellers ser det super ud!

2024-03-19 08:20 UTC, zteffano commented on hello_app/views.py
> +
Skal ikke være her - er lagt over i notes.py :-)

2024-03-19 09:03 UTC, zteffano requested changes

2024-03-19 09:03 UTC, zteffano commented on hello_app/API.py
> +@api.route('/note', methods=['GET'])
Når nu der henter alle notes, så er det "best practice" at kalde den /notes

2024-03-19 09:40 UTC, zteffano approved these changes
Godt arbejde dauer!

2024-03-19 09:40 UTC, merged