Edit/Delete auth på plads. Venter på db ændringer.
PBI22/Agil-Flask-Note-Projekt pull request #46
Opened 2024-03-19 12:23 UTC by zimula

2024-03-19 13:51 UTC, zteffano requested changes
Mange ting der breaker appen her :( Du mangler bl.a. også en __init__.py fil. 

Den kan ikke engang starte op og mange ting jeg ikke helt kan få til at give mening.

Har forsøgt på bedste vis at skrive nogle kommentarer og pointere nogle af stederne.

Til sidst, så tænker jeg det havde været nemmere at arbejde med når vores Database er blevet ændret.

2024-03-19 13:51 UTC, zteffano commented on hello_app/auth.py
> -            app.logger.warning(f"Failed login attempt from: {request.remote_addr} with username: {username}")
...Hvorfor sletter du denne logging  ?

2024-03-19 13:51 UTC, zteffano commented on hello_app/auth.py
> +    # If request method is GET, render the login template
Der er angivet 2 returns , som er akkurat det samme

2024-03-19 13:51 UTC, zteffano commented on hello_app/utils.py
> +            upd.author = user['username']
Dette skal ikke være brugernavnet, men foreign key til account fra notes. Den vil aldrig kunne redigere en note, da modellen/ databasen ikke tillader dette

2024-03-19 13:51 UTC, zteffano commented on hello_app/utils.py
> +        if user['username'] == upd.author or user['role'] == 'Admin':#admin skal tage fra db
en bruger vil ikke kunne rette sin egne noter, fordi upd.author er en INT / Foreign key til accountID og ikke en string med usernamet

2024-03-19 13:51 UTC, zteffano commented on hello_app/utils.py
> +        app.logger.error(f"Failed to edit note: {e} from user: {session.get('user')}")
Eftersom du ændre i session['user'] til en dict med username og role, breaker det alt logging, som nu ikke korrekt viser brugernavne hele vejen rundt

2024-03-19 13:51 UTC, zteffano commented on hello_app/auth.py
> -            session['user'] = account.username
Når du ændre dette, breaker du mere eller mindre alt, der har implementeret og bruger denne løsning.  Hvis du skal ændre noget så grundlæggende, er det vigtigt lige at cleare det og så skal det gøres alle steder hvor der refereres til det, hvis user bliver brugt til direkte at arbejder med brugernavnet.

hvorfor ikke bare lave en session['role'] og tilføje den, istedet? så kan du bruge den uden at ændre på den anden

2024-03-19 13:51 UTC, zteffano commented on hello_app/utils.py
> +        if 'user' not in session:
Vi har allerede en @login_required på edit endpoint, så den her er unødvendig

2024-03-19 13:53 UTC, zteffano commented
Til sidste kunne det være rart du skrev i dit pull request hvad der blev tilføjet til kodebasen og lidt info til os der ikke har siddet med koden.

2024-03-19 20:44 UTC, zimula commented on hello_app/utils.py
> +            upd.author = user['username']
det er accountid'en der gemt heri

2024-03-19 20:50 UTC, zimula commented on hello_app/auth.py
> -            session['user'] = account.username
eller tilføje en key:value pair mere

2024-03-19 20:51 UTC, zimula commented on hello_app/auth.py
> +    # If request method is GET, render the login template
typo

2024-03-20 08:31 UTC, zimula commented on hello_app/utils.py
> +        app.logger.error(f"Failed to edit note: {e} from user: {session.get('user')}")
fixed

2024-03-20 08:31 UTC, zimula commented on hello_app/auth.py
> -            session['user'] = account.username
fixed

2024-03-20 08:36 UTC, closed without merging