Tilføjede info om implementation af sikkerhed i flask
PBI22/Agil-Flask-Note-Projekt pull request #6
Opened 2024-03-12 11:36 UTC by marcusbvn

2024-03-12 11:43 UTC, zimula commented
Makes sense. Excellent

2024-03-12 11:44 UTC, zteffano requested changes
Synes det super og konkret med teksten der er i md filen, dejligt forståligt skrevet.

- Kunne være fedt hvis der var nogle konkrete indlejret eksempler i markdown filen. i kan evt. bruge ```python til at skrive kode eksempler direkte ind, så man ikke skal over på en chatgpt historik.


Synes der for meget information, i chatgpt historikken. Kan man ikke samle og kode det ind i samme md fil - og så bare lige med eksempel på parameterized queries, og de 3-4 nøglebegreber der er, som konkrete eksempler i kode? :-)

2024-03-12 12:45 UTC, majorSLATTER approved these changes
Super!

2024-03-13 09:13 UTC, zteffano requested changes
Begynder satme at se skarpt ud!

Kunne man ikke splitte python og javascript op og så bruge korrekt markdown syntax , så der syntax highlight på`?

Så det nemt at læse

2024-03-13 09:28 UTC, zteffano requested changes
Kunne være fedt lige at få alt koden pakket ind i code syntaxes, så det læsbar og ikke bliver "klemt" sammen på en linje

2024-03-13 09:28 UTC, zteffano commented on Artefakter/Sikkerhed/Implementation.md
> +<script>document.write('<script>x="'+jsEscape(untrustedValue)+'";<\/script>')</script>
js

2024-03-13 09:28 UTC, zteffano commented on Artefakter/Sikkerhed/Implementation.md
> +function jsEscape(str){
js

2024-03-13 09:28 UTC, zteffano commented on Artefakter/Sikkerhed/Implementation.md
> +<script>document.body.innerHTML = htmlEncode(untrustedValue)</script>
js

2024-03-13 09:53 UTC, zteffano approved these changes
Smukt  - fed opsætning Mr Markdown;-)

2024-03-13 09:59 UTC, merged