tilføjede swagger og fiksede begrænsning af adgang til sletning/edit
PBI22/Agil-Flask-Note-Projekt pull request #93
Opened 2024-05-01 07:09 UTC by MartinDP333

Swagger kan findes i url/apidocs
eksempelvis:
http://127.0.0.1:5000/apidocs/#/

Har tilføjede 2 nye biblioteker
flasgger
flask_swagger_ui

Har lavet en ny mappe i static folder som hedder jsonformatting
den indeholder yml filer som skaber struktur til swagger

Har tilføjede ny funktion som checker om url er "swagger" eller om der er en valid jwt (dette virker ikke 100% sikkert, men tænker det vil tage for langt tid at implementere en mere sikker løsning)
I hvert endpoint har vi en ny routing som går til den nye yml fil for at fremhæve det i swagger
eksempelvis:
@swag_from('static/swaggerformatting/login.yml')

2024-05-01 08:19 UTC, zteffano requested changes
Virker super lokalt  - Der er blot den RESTful naming convention vi snakkede om på Discord, link er også her:
https://restfulapi.net/resource-naming/

og hvis muligt, så at f.eks. noteID står øverst når vi henter note via swagger.

Ellers super :-)

2024-05-01 11:23 UTC, MartinDP333 commented
har ikke tilføjede rækkefølge til json så noteid er i toppen
jeg prøvede at flytte rundt på det ved at lave en dictionary og manuelt flytte rundt på ting
tror det er jsonify der alfabetisere det, har prøvet at se om man kunne ændre det, men fandt ikke noget
![billede](https://github.com/PBI22/Agil-Flask-Note-Projekt/assets/91844700/55784c95-7db5-4974-a692-c479624551a1)
fandt dette som muligvis siger at man ikke skal tænke over orderen siden json er unordered som de selv siger på deres hjemmeside https://www.json.org/json-en.html
![billede](https://github.com/PBI22/Agil-Flask-Note-Projekt/assets/91844700/335718ab-529d-41f0-8c76-32adb1f788d0)
så er spørgsmålet bare, hvis det ikke er vigtigt at de er ordered, hvorfor alfabetisere jsonify det?
Tænker ikke det er det største problem, hvis man henter fra en api, så vil man nok bare order det i ens program i stedet?

har rettet endpoints så de bedre følger restful api naming conventions
og har fjernet print() fra delete endpoint
derudover er API dokumentation stille på vej

2024-05-02 07:38 UTC, majorSLATTER approved these changes
Ser super godt ud! Og det virker!
Godt med naming og ingen print statements!

2024-05-02 07:46 UTC, zteffano approved these changes
Super godt Dauer. 

Dejligt med Informationen på JSON ordering. Det giver god mening :-)

2024-05-02 07:46 UTC, merged